# Generated by Django 2.1.7 on 2019-02-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='token',
            field=models.CharField(max_length=150, verbose_name='Token'),
        ),
    ]
