# Generated by Django 2.1.7 on 2019-02-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20190224_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
