# Generated by Django 2.1.7 on 2019-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20190224_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='dominio',
            field=models.URLField(max_length=150),
        ),
    ]
