# Generated by Django 2.1.7 on 2019-02-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20190224_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceso',
            options={'verbose_name': 'Acceso', 'verbose_name_plural': 'Accesos'},
        ),
    ]
