# Generated by Django 2.1.7 on 2019-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20190224_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='servicio',
            field=models.CharField(default='ss', max_length=50, verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
