# Generated by Django 2.1.7 on 2019-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_evento_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='cueenta',
            new_name='cuenta',
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default='dd', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
