# Generated by Django 2.1.7 on 2019-02-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_auto_20190225_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cuenta',
        ),
    ]
