# Generated by Django 2.1.7 on 2019-02-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_remove_evento_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cuenta', models.CharField(max_length=150, verbose_name='Cuenta')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'verbose_name': 'Institució',
            },
        ),
    ]
